USE yt_ecommerce;

INSERT INTO product_images (product_id, images) VALUES (1, '/images/OIP (40).jpg');
INSERT INTO product_images (product_id, images) VALUES (2, '/images/beautiful-women-leather-handbag-generative-ai-photo.jpg');
INSERT INTO product_images (product_id, images) VALUES (3, '/images/OIP (32).jpg');
INSERT INTO product_images (product_id, images) VALUES (4, '/images/OIP (70).jpg');
INSERT INTO product_images (product_id, images) VALUES (5, '/images/OIP (21).jpg');
INSERT INTO product_images (product_id, images) VALUES (6, '/images/6e601f1018cbf97434d377c1a18eb293.jpg');
INSERT INTO product_images (product_id, images) VALUES (7, '/images/sadi6.jpg');
INSERT INTO product_images (product_id, images) VALUES (8, '/images/shree_1.jpg');
INSERT INTO product_images (product_id, images) VALUES (9, '/images/OIP (7).jpg');
INSERT INTO product_images (product_id, images) VALUES (10, '/images/OIP (78).jpg');
INSERT INTO product_images (product_id, images) VALUES (11, '/images/blue-sofa-isolated-generative-ai-free-photo.jpg');
INSERT INTO product_images (product_id, images) VALUES (12, '/images/OIP (41).jpg');
INSERT INTO product_images (product_id, images) VALUES (13, '/images/OIP (25).jpg');
INSERT INTO product_images (product_id, images) VALUES (14, '/images/55dd3b2a123e07512ab874e39c4ed098.jpg');
INSERT INTO product_images (product_id, images) VALUES (15, '/images/SS0453G-BLGY-1_5e4c850c-47e1-4d80-8359-4405cfe63d60.webp');
INSERT INTO product_images (product_id, images) VALUES (16, '/images/sht.jpg');
INSERT INTO product_images (product_id, images) VALUES (17, '/images/ai-generated-earphone-isolated-on-transparent-background-free-png.png');
INSERT INTO product_images (product_id, images) VALUES (18, '/images/Apple-Watch-Series-10-aluminum-rose-gold-240909_inline.jpg.large_2x.jpg');
INSERT INTO product_images (product_id, images) VALUES (19, '/images/pexels-webdonut-19090.jpg');
INSERT INTO product_images (product_id, images) VALUES (20, '/images/stuart-weitzman-stuart-weitzman-nudist-ii-sandal-100-i-32715621.jpg');
INSERT INTO product_images (product_id, images) VALUES (21, '/images/199ab764-f112-4508-888c-86a1094624e8.17daf90b726900a539a8b9873fdea1f5.avif');
INSERT INTO product_images (product_id, images) VALUES (22, '/images/OIP (6).jpg');
INSERT INTO product_images (product_id, images) VALUES (23, '/images/OIP (63).jpg');
INSERT INTO product_images (product_id, images) VALUES (24, '/images/OIP (36).jpg');
INSERT INTO product_images (product_id, images) VALUES (25, '/images/OIP (71).jpg');
INSERT INTO product_images (product_id, images) VALUES (26, '/images/OIP (28).jpg');
INSERT INTO product_images (product_id, images) VALUES (27, '/images/81pw8RzbKaL.jpg');
INSERT INTO product_images (product_id, images) VALUES (28, '/images/pexels-pixabay-248528.jpg');
INSERT INTO product_images (product_id, images) VALUES (29, '/images/OIP (14).jpg');
INSERT INTO product_images (product_id, images) VALUES (30, '/images/8d3572586c43b85633d172063ff45cb8.jpg');
INSERT INTO product_images (product_id, images) VALUES (31, '/images/sony.jpg');
INSERT INTO product_images (product_id, images) VALUES (32, '/images/stripe.png');
INSERT INTO product_images (product_id, images) VALUES (33, '/images/71zU9IP2miL._AC_UY1000_.jpg');
INSERT INTO product_images (product_id, images) VALUES (34, '/images/OIP (54).jpg');
INSERT INTO product_images (product_id, images) VALUES (35, '/images/samsung.jpg');
INSERT INTO product_images (product_id, images) VALUES (36, '/images/istockphoto-180756294-612x612.jpg');
INSERT INTO product_images (product_id, images) VALUES (37, '/images/Apple-Watch-Family-Setup-220907_big.jpg.large_2x.jpg');
INSERT INTO product_images (product_id, images) VALUES (38, '/images/OIP (95).jpg');
INSERT INTO product_images (product_id, images) VALUES (39, '/images/blue-jeans-a-pile-of-denim-pants-element-modern-women-and-men-fashion-pants-texture-isolated-on-white-background-free-photo.jpg');
INSERT INTO product_images (product_id, images) VALUES (40, '/images/OIP (20).jpg');
INSERT INTO product_images (product_id, images) VALUES (41, '/images/OIP (51).jpg');
INSERT INTO product_images (product_id, images) VALUES (42, '/images/Tvirat.jpg');
INSERT INTO product_images (product_id, images) VALUES (43, '/images/rashmika2.jpg');
INSERT INTO product_images (product_id, images) VALUES (44, '/images/OIP (75).jpg');
INSERT INTO product_images (product_id, images) VALUES (45, '/images/OIP (85).jpg');
INSERT INTO product_images (product_id, images) VALUES (46, '/images/71Jo1GnRwKL._UL1500_.jpg');
INSERT INTO product_images (product_id, images) VALUES (47, '/images/oxford-shoes-6078993_1280.jpg');
INSERT INTO product_images (product_id, images) VALUES (48, '/images/OIP (66).jpg');
INSERT INTO product_images (product_id, images) VALUES (49, '/images/Paithani-sadi-design.jpg');
INSERT INTO product_images (product_id, images) VALUES (50, '/images/OIP (64).jpg');
INSERT INTO product_images (product_id, images) VALUES (51, '/images/OIP (84).jpg');
INSERT INTO product_images (product_id, images) VALUES (52, '/images/OIP (77).jpg');
INSERT INTO product_images (product_id, images) VALUES (53, '/images/63f7126c-f6a3-47ba-9755-705a8865abd3_1340x1786.jpeg.a.jpeg');
INSERT INTO product_images (product_id, images) VALUES (54, '/images/img1.jpg');
INSERT INTO product_images (product_id, images) VALUES (55, '/images/OIP (82).jpg');
INSERT INTO product_images (product_id, images) VALUES (56, '/images/OIP (60).jpg');
INSERT INTO product_images (product_id, images) VALUES (57, '/images/OIP (26).jpg');
INSERT INTO product_images (product_id, images) VALUES (58, '/images/OIP (48).jpg');
INSERT INTO product_images (product_id, images) VALUES (59, '/images/OIP (35).jpg');
INSERT INTO product_images (product_id, images) VALUES (60, '/images/Apple-Watch-Series-11-display-250909_big.jpg.large_2x.jpg');
INSERT INTO product_images (product_id, images) VALUES (61, '/images/OIP (29).jpg');
INSERT INTO product_images (product_id, images) VALUES (62, '/images/OIP (89).jpg');
INSERT INTO product_images (product_id, images) VALUES (63, '/images/janvi.jpg');
INSERT INTO product_images (product_id, images) VALUES (64, '/images/OIP.jpg');
INSERT INTO product_images (product_id, images) VALUES (65, '/images/OIP (91).jpg');
INSERT INTO product_images (product_id, images) VALUES (66, '/images/shoe-sneakers-footwear-54334.jpg');
INSERT INTO product_images (product_id, images) VALUES (67, '/images/watch2.jpg');
INSERT INTO product_images (product_id, images) VALUES (68, '/images/ee1840e1-d589-498f-810c-0d4ee6cc9a4e.f05cdc65e3976a4b7af1aec5806d8034.avif');
INSERT INTO product_images (product_id, images) VALUES (69, '/images/Nidhi-Agarwal-Hot-Pics-in-Yellow-Saree-3.jpg');
INSERT INTO product_images (product_id, images) VALUES (70, '/images/81tLpL0CuLL._UL1500_.jpg');
INSERT INTO product_images (product_id, images) VALUES (71, '/images/Nauvari-sadi-design.jpg');
INSERT INTO product_images (product_id, images) VALUES (72, '/images/91AuzGj5aSL._UL1500_.jpg');
INSERT INTO product_images (product_id, images) VALUES (73, '/images/Net-sadi-design-3.jpg');
INSERT INTO product_images (product_id, images) VALUES (74, '/images/burds.jpg');
INSERT INTO product_images (product_id, images) VALUES (75, '/images/OIP (45).jpg');
INSERT INTO product_images (product_id, images) VALUES (76, '/images/OIP (5).jpg');
INSERT INTO product_images (product_id, images) VALUES (77, '/images/OIP (69).jpg');
INSERT INTO product_images (product_id, images) VALUES (78, '/images/OIP (59).jpg');
INSERT INTO product_images (product_id, images) VALUES (79, '/images/img3.jpg');
INSERT INTO product_images (product_id, images) VALUES (80, '/images/71gvH4h5dqL._SL1500_.jpg');
INSERT INTO product_images (product_id, images) VALUES (81, '/images/OIP (96).jpg');
INSERT INTO product_images (product_id, images) VALUES (82, '/images/sadi5.jpg');
INSERT INTO product_images (product_id, images) VALUES (83, '/images/OIP (43).jpg');
INSERT INTO product_images (product_id, images) VALUES (84, '/images/OIP (33).jpg');
INSERT INTO product_images (product_id, images) VALUES (85, '/images/OIP (2).jpg');
INSERT INTO product_images (product_id, images) VALUES (86, '/images/OIP (22).jpg');
INSERT INTO product_images (product_id, images) VALUES (87, '/images/OIP (42).jpg');
INSERT INTO product_images (product_id, images) VALUES (88, '/images/71I-cik1CyL._AC_UL1500_.jpg');
INSERT INTO product_images (product_id, images) VALUES (89, '/images/clothes-for-a-modern-lady-ensemble-with-pink-color-jacket-bag-jeans-jewelry-and-shoes-closeup-ai-generative-photo.jpg');
INSERT INTO product_images (product_id, images) VALUES (90, '/images/amar.png');
INSERT INTO product_images (product_id, images) VALUES (91, '/images/img4.jpg');
INSERT INTO product_images (product_id, images) VALUES (92, '/images/OIP (3).jpg');
INSERT INTO product_images (product_id, images) VALUES (93, '/images/feet-1840619_1280.jpg');
INSERT INTO product_images (product_id, images) VALUES (94, '/images/Soft-silk-sadi-2.jpg');
INSERT INTO product_images (product_id, images) VALUES (95, '/images/OIP (80).jpg');
INSERT INTO product_images (product_id, images) VALUES (96, '/images/OIP (88).jpg');
INSERT INTO product_images (product_id, images) VALUES (97, '/images/walking-sandals-nh100-men-s-quechua-8583453.avif');
INSERT INTO product_images (product_id, images) VALUES (98, '/images/maxresdefault (1).jpg');
INSERT INTO product_images (product_id, images) VALUES (99, '/images/Apple-Watch-Series-10-Smart-Stack-240909_inline.jpg.large_2x.jpg');
INSERT INTO product_images (product_id, images) VALUES (100, '/images/51tKgJyDgML._SL1496_.jpg');
INSERT INTO product_images (product_id, images) VALUES (101, '/images/Bandhej-sadi-design-3.jpg');
INSERT INTO product_images (product_id, images) VALUES (102, '/images/men-closed-toe-leather-luxury-sandals-brown-2-smd-online-coimbatore-1000x1000.jpg');
INSERT INTO product_images (product_id, images) VALUES (103, '/images/OIP (44).jpg');
INSERT INTO product_images (product_id, images) VALUES (104, '/images/OIP (81).jpg');
INSERT INTO product_images (product_id, images) VALUES (105, '/images/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTA5L3Jhd3BpeGVsX29mZmljZV8zMV9waG90b19vZl9hX2xhcHRvcF9tb2NrdXBfY2xvc2UtdXBfbWluaW1hbF9pc182M2Q2NzViOS00YjlhLTQ3OWEtOGMyMS1hYWQwMjViNWYzZDIucG5n.jpg');
INSERT INTO product_images (product_id, images) VALUES (106, '/images/Tshirt2.jpg');
INSERT INTO product_images (product_id, images) VALUES (107, '/images/OIP (13).jpg');
INSERT INTO product_images (product_id, images) VALUES (108, '/images/ear-pods-on-transparent-background-png.png');
INSERT INTO product_images (product_id, images) VALUES (109, '/images/iphone2.jpg');
INSERT INTO product_images (product_id, images) VALUES (110, '/images/OIP (46).jpg');
INSERT INTO product_images (product_id, images) VALUES (111, '/images/OIP (4).jpg');
INSERT INTO product_images (product_id, images) VALUES (112, '/images/OIP (8).jpg');
INSERT INTO product_images (product_id, images) VALUES (113, '/images/Plain-sadi-design-2.jpg');
INSERT INTO product_images (product_id, images) VALUES (114, '/images/OIP (76).jpg');
INSERT INTO product_images (product_id, images) VALUES (115, '/images/tshirt-8726716_1280.jpg');
INSERT INTO product_images (product_id, images) VALUES (116, '/images/night-pants-500x500.webp');
INSERT INTO product_images (product_id, images) VALUES (117, '/images/OIP (27).jpg');
INSERT INTO product_images (product_id, images) VALUES (118, '/images/SAEDASANDAL100EWA_000757_CAMPAIGN.jpg');
INSERT INTO product_images (product_id, images) VALUES (119, '/images/OIP (24).jpg');
INSERT INTO product_images (product_id, images) VALUES (120, '/images/OIP (57).jpg');
INSERT INTO product_images (product_id, images) VALUES (121, '/images/Plain-sadi-design-3.jpg');
INSERT INTO product_images (product_id, images) VALUES (122, '/images/51fH0mZaG4L._AC_.jpg');
INSERT INTO product_images (product_id, images) VALUES (123, '/images/watch.jpg');
INSERT INTO product_images (product_id, images) VALUES (124, '/images/samsunge26.jpg');
INSERT INTO product_images (product_id, images) VALUES (125, '/images/shirt.jpg');
INSERT INTO product_images (product_id, images) VALUES (126, '/images/OIP (39).jpg');
INSERT INTO product_images (product_id, images) VALUES (127, '/images/OIP (47).jpg');
INSERT INTO product_images (product_id, images) VALUES (128, '/images/HD-wallpaper-sai-pallavi-ka-indian-culture-look-south-indian-saree-white-saree-actress.jpg');
INSERT INTO product_images (product_id, images) VALUES (129, '/images/luxury-leather-handbag-and-minimalistic-backdrop-created-with-generative-ai-photo.jpg');
INSERT INTO product_images (product_id, images) VALUES (130, '/images/OIP (12).jpg');
INSERT INTO product_images (product_id, images) VALUES (131, '/images/jaygodgodh8774-Luxurious-mens-silk-shirt-featuring-an-exquisite-a1b22fe1-04b0-4622-9ea4-99453b2c7733.webp');
INSERT INTO product_images (product_id, images) VALUES (132, '/images/OIP (87).jpg');
INSERT INTO product_images (product_id, images) VALUES (133, '/images/OIP (53).jpg');
INSERT INTO product_images (product_id, images) VALUES (134, '/images/Tshirt.jpg');
INSERT INTO product_images (product_id, images) VALUES (135, '/images/OIP (73).jpg');
INSERT INTO product_images (product_id, images) VALUES (136, '/images/OIP (97).jpg');
INSERT INTO product_images (product_id, images) VALUES (137, '/images/711WQcViKyL.jpg');
INSERT INTO product_images (product_id, images) VALUES (138, '/images/OIP (56).jpg');
INSERT INTO product_images (product_id, images) VALUES (139, '/images/OIP (90).jpg');
INSERT INTO product_images (product_id, images) VALUES (140, '/images/men-check-shirt.jpg');
INSERT INTO product_images (product_id, images) VALUES (141, '/images/OIP (31).jpg');
INSERT INTO product_images (product_id, images) VALUES (142, '/images/OIP (11).jpg');
INSERT INTO product_images (product_id, images) VALUES (143, '/images/1984-cd-40-cd-401-sq.avif');
INSERT INTO product_images (product_id, images) VALUES (144, '/images/sadi4.jpg');
INSERT INTO product_images (product_id, images) VALUES (145, '/images/sadi2.jpg');
INSERT INTO product_images (product_id, images) VALUES (146, '/images/OIP (94).jpg');
INSERT INTO product_images (product_id, images) VALUES (147, '/images/Puma.jpg');
INSERT INTO product_images (product_id, images) VALUES (148, '/images/849ad0d9431ecb0c8e9286966df999ad.jpg');
INSERT INTO product_images (product_id, images) VALUES (149, '/images/OIP (49).jpg');
INSERT INTO product_images (product_id, images) VALUES (150, '/images/OIP (58).jpg');
INSERT INTO product_images (product_id, images) VALUES (151, '/images/rashmika1.jpg');
INSERT INTO product_images (product_id, images) VALUES (152, '/images/OIP (34).jpg');
INSERT INTO product_images (product_id, images) VALUES (153, '/images/OIP (15).jpg');
INSERT INTO product_images (product_id, images) VALUES (154, '/images/Fancy-sadi-design.jpg');
INSERT INTO product_images (product_id, images) VALUES (155, '/images/ceiling-fan-decoration-interior-in-the-room-photo.jpg');
INSERT INTO product_images (product_id, images) VALUES (156, '/images/e1f2905b-c54c-4a11-974c-88efb8fdd72f1717649231907-Mens-Casual-Denim-Shirt-4191717649231448-1.jpg');
INSERT INTO product_images (product_id, images) VALUES (157, '/images/OIP (50).jpg');
INSERT INTO product_images (product_id, images) VALUES (158, '/images/sadi1.jpg');
INSERT INTO product_images (product_id, images) VALUES (159, '/images/Stone-work-sadi-design-2.jpg');
INSERT INTO product_images (product_id, images) VALUES (160, '/images/Soft-silk-sadi.jpg');
INSERT INTO product_images (product_id, images) VALUES (161, '/images/1603599242_fastrack-audio-sunglasses-1.avif');
INSERT INTO product_images (product_id, images) VALUES (162, '/images/OIP (9).jpg');
INSERT INTO product_images (product_id, images) VALUES (163, '/images/img2.jpg');
INSERT INTO product_images (product_id, images) VALUES (164, '/images/51KTR0+bwUL._SL1100_.jpg');
INSERT INTO product_images (product_id, images) VALUES (165, '/images/Elabch-Womens-Plus-Size-Underwear-100-Cotton-Underwear-High-Waisted-Briefs-Full-Coverage-Panties-for-Women-XL-6XL_adc5adf8-6307-4a82-8c1b-82086bcf70ef.53cb4e02654d19170a21f4d3b880ebda.avif');
INSERT INTO product_images (product_id, images) VALUES (166, '/images/Lehenga-sadi-design.jpg');
INSERT INTO product_images (product_id, images) VALUES (167, '/images/ee668a6c250b9f783d52d9f80828a80f.jpg');
INSERT INTO product_images (product_id, images) VALUES (168, '/images/OIP (74).jpg');
INSERT INTO product_images (product_id, images) VALUES (169, '/images/nidhi.jpg');
INSERT INTO product_images (product_id, images) VALUES (170, '/images/chapal.jpg');
INSERT INTO product_images (product_id, images) VALUES (171, '/images/OIP (18).jpg');
INSERT INTO product_images (product_id, images) VALUES (172, '/images/a2d933d0710f630686322e3289b9896a.jpg');
INSERT INTO product_images (product_id, images) VALUES (173, '/images/61ofV82kMKL._SL1080_.jpg');
INSERT INTO product_images (product_id, images) VALUES (174, '/images/OIP (65).jpg');
INSERT INTO product_images (product_id, images) VALUES (175, '/images/OIP (16).jpg');
INSERT INTO product_images (product_id, images) VALUES (176, '/images/Sadi-Ke-Blouse-Ke-Design.jpg');
INSERT INTO product_images (product_id, images) VALUES (177, '/images/OIP (38).jpg');
INSERT INTO product_images (product_id, images) VALUES (178, '/images/Printed-sadi-design-2.jpg');
INSERT INTO product_images (product_id, images) VALUES (179, '/images/Lehenga-sadi-design-3.jpg');
INSERT INTO product_images (product_id, images) VALUES (180, '/images/pair-of-blue-running-sneakers-on-white-background-isolated-photo.jpg');
INSERT INTO product_images (product_id, images) VALUES (181, '/images/OIP (72).jpg');
INSERT INTO product_images (product_id, images) VALUES (182, '/images/OIP (79).jpg');
INSERT INTO product_images (product_id, images) VALUES (183, '/images/OIP (67).jpg');
INSERT INTO product_images (product_id, images) VALUES (184, '/images/Ceiling-Fan-PNG-HD.png');
INSERT INTO product_images (product_id, images) VALUES (185, '/images/OIP (68).jpg');
INSERT INTO product_images (product_id, images) VALUES (186, '/images/pexels-theamritdev-36523504.jpg');
INSERT INTO product_images (product_id, images) VALUES (187, '/images/img0.jpg');
INSERT INTO product_images (product_id, images) VALUES (188, '/images/0223f7726c74c1ca47b1e8820eb1b661.jpg');
INSERT INTO product_images (product_id, images) VALUES (189, '/images/7c052579112694f094b19529a2c92b28.jpg');
INSERT INTO product_images (product_id, images) VALUES (190, '/images/OIP (52).jpg');
INSERT INTO product_images (product_id, images) VALUES (191, '/images/OIP (62).jpg');
INSERT INTO product_images (product_id, images) VALUES (192, '/images/Untitled-design-2-18-768x768.webp');
